# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: roman-wfi-reference-pipeline

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@712eefadba5f7096ac20767477bcca870b150b98 # initial
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@712eefadba5f7096ac20767477bcca870b150b98 # initial
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip dependencies
      uses: actions/cache@712eefadba5f7096ac20767477bcca870b150b98 # initial
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install .[test]
    - name: Ruff Test
      run: |
        ruff check ./src
    - name: Pytest with coverage
      run: |
        pytest --cov=wfi_reference_pipeline --cov-report=xml
